spring.application.name=basic-rest-api
spring.datasource.url=jdbc:h2:file:./data/basic-rest-api-db
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=update
